(define (problem tuske83)
(:domain tuske8)
(:objects peg1 peg2 peg3 d1 d2 red blue)
(:init (smaller peg1 d1) (smaller peg1 d2) 
	(smaller peg2 d1) (smaller peg2 d2) 
   	(smaller peg3 d1) (smaller peg3 d2) 
   	(smaller d2 d1) 
	(clear peg2) (clear peg3) (clear d1)
	(on d2 peg1) (on d1 d2)
	(color d1 red) (color d2 red) (color peg1 blue) (color peg2 blue) (color peg3 blue))

(:goal (and (on d1 d2) (or (and (color d1 red) 
(color d2 red) ) (and (color d1 blue) 
(color d2 blue))))))