(define (domain tuske8)
(:requirements :strips :equality)
(:predicates (clear ?x)
		(on ?x ?y)
		(smaller ?x ?y)
		(color ?x ?y))

(:action move
:parameters (?disc ?c ?from ?to ?tocolor)
:precondition (and (smaller ?to ?disc)
			(on ?disc ?from)
			(clear ?disc)
			(clear ?to)
			(color ?disc ?c)
			(color ?to ?tocolor)
			(not (= ?c ?tocolor )))
:effect (and (clear ?from)
		(on ?disc ?to)
		(not (on ?disc ?from))
		(not (clear ?to))
		(not (color ?disc ?c))
		(color ?disc ?tocolor))
))